version: "2"

services:
  php:
    container_name: open_loyalty_backend
    build:
      context: '../'
      dockerfile: './docker/dev/php/fpm-dockerfile'
    restart: always
    links:
      - db
      - elk
      - mail
    ports:
      - "9000:9000"
    volumes:
        - '../backend:/var/www/openloyalty'
    # command: phing setup
    env_file:
        - .env
  nginx:
    container_name: open_loyalty_frontend
    build:
      context: '../'
      dockerfile: './docker/dev/web/backend-dockerfile'
    restart: always
    links:
      - php
    ports:
      - "8888:80"
  frontend:
    container_name: open_loyalty_frontend_dev
    build:
      context: '../'
      dockerfile: './docker/dev/web/front-dockerfile'
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - '../frontend/:/var/www/frontend'
      - './dev/web/config.js:/var/www/frontend/src/config.js'
  elk:
    container_name: open_loyalty_elk
    build:
      context: '../'
      dockerfile: './docker/base/elasticsearch-dockerfile'
    restart: always
    volumes:
      - ./dev/elk/data:/usr/share/elasticsearch/data
      - ./dev/elk/config:/usr/share/elasticsearch/config
      - ./dev/elk/plugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200"
  db:
    container_name: open_loyalty_db
    image: postgres:9
    ports:
      - "5432:5432"
    restart: always
    env_file:
        - .env
  mail:
    container_name: open_loyalty_mail
    image: mailhog/mailhog
    restart: always
    ports:
      - "8186:8025"