version: "2"

services:
  php:
    container_name: open_loyalty_backend
    cpus: "2"
    mem_reservation: "100M"
    mem_limit: "2G"
    build:
      context: '../'
      dockerfile: './docker/dev/php/fpm-dockerfile'
    restart: always
    links:
      - db
      - elk
      - mail
    ports:
      - "9000:9000"
    volumes:
      - '../backend:/var/www/openloyalty'
    # command: phing setup
    env_file:
        - .env
    networks:
          - dockernet
  nginx:
    container_name: open_loyalty_frontend
    cpus: "0.5"
    mem_reservation: "10M"
    mem_limit: "250M"
    build:
      context: '../'
      dockerfile: './docker/dev/web/backend-dockerfile'
    restart: always
    links:
      - php
    ports:
      - "8888:80"
    networks:
          - dockernet
  frontend:
    container_name: open_loyalty_frontend_dev
    cpus: "2"
    mem_reservation: "50M"
    mem_limit: "1G"
    build:
      context: '../'
      dockerfile: './docker/dev/web/front-dockerfile'
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - '../frontend/:/var/www/frontend'
      - './dev/web/config.js:/var/www/frontend/src/config.js'
    networks:
          - dockernet
  elk:
    container_name: open_loyalty_elk
    build:
      context: '../'
      dockerfile: './docker/base/elasticsearch-dockerfile'
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ingest.geoip.downloader.enabled=false"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    mem_limit: 4g
    volumes:
      - ./dev/elk/data/:/usr/share/elasticsearch/data/
      - ./dev/elk/plugins/:/usr/share/elasticsearch/plugins/
    ports:
      - "9200:9200"
    networks:
          - dockernet
  db:
    container_name: open_loyalty_db
    cpus: "0.5"
    mem_reservation: "10M"
    mem_limit: "250M"
    image: postgres:9
    volumes:
      - ./dev/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    env_file:
        - .env
    networks:
          - dockernet
  mail:
    container_name: open_loyalty_mail
    cpus: "0.5"
    mem_reservation: "10M"
    mem_limit: "250M"
    image: mailhog/mailhog
    restart: always
    ports:
      - "8186:8025"
    networks:
          - dockernet
networks:
    dockernet:
        driver: 
        ipam:
            config:
            - subnet: 192.168.0.0/24
              gateway: 192.168.0.1